### ISSUE TITLE
Uncaught SyntaxError: The requested module ... does not provide an export named 'default'

### ISSUE THREAD

**Issue by pi0** [nuxt/vite#56]
Affected dependencies:
- ufo
- date-fns
- nanoid

Vite's dep-optimization, generates an entry like this for client:

```js
import __vite__cjsImport1_ufo from "/@fs/..../node_modules/.cache/vite/client/ufo.js?v=5294cbe1";
const _isSamePath = __vite__cjsImport1_ufo["isSamePath"];
```

But since dependencies like ufo use named esm exports (`export { ... }`), it generates an error like this:

```
Uncaught SyntaxError: The requested module ... does not provide an export named 'default'
```

Current workaround, is to either use `alias` option to resolve such deps to CJS version or exclude them via `optimizeDeps.exclude`:

```js
// nuxt.config
export default {
  vite: {
    optimizeDeps: {
      exclude: [
        'date-fns'
      ]
    }
  }
}
```

Other variant (#62): SyntaxError: import not found: default

**Comment by thefoxie** [comment]
@pi0 I've created #58 but it's probably related to this. None of the workarounds work for me.

**Comment by saadallahdev** [comment]
Uncaught SyntaxError: The requested module '/@id/E:/SaadallahDev/My%20Project/Manhal/Manhal/Manhaly.com/node_modules/cookie/index.js?v=0671a158' does not provide an export named 'default'

**Comment by saadallahdev** [comment]
how I can execute the cookie model I think this happen because of nuxt auth

**Comment by yassipad** [comment]
Those are three modules that throw the same error right now:
- d3
- @vueuse/core
- @heroicons/vue

Thanks for the great package !

**Comment by maoosi** [comment]
> Uncaught SyntaxError: The requested module '..../node_modules/cookie/index.js?v=0671a158' does not provide an export named 'default'

I am also having the same issue when using the `@nuxtjs/auth-next` package. Adding `cookie` or `@nuxtjs/auth-next` to the exclude list does not resolve it. Suggestions welcomed!

**Comment by CodeDredd** [comment]
An working workaround for me was not to use `exlude` but `include`. A hint and explanation can be found here: https://github.com/vitejs/vite/issues/2579 
````
...
  optimizeDeps: {
    include: [
      'cookie'
    ]
  }
...
````

Now i am stucked with the composition-api bug with `require` ^^

**Comment by hojas** [comment]
![image](https://user-images.githubusercontent.com/4729039/118608454-4acc4d00-b7ec-11eb-8d67-51412d2c45e5.png)

**Comment by duongnamvt** [comment]
I got and error with @fs too :(. I just disable vite to keep my project go on

**Comment by toniengelhardt** [comment]
Uncaught SyntaxError: The requested module '/node_modules/vue-calendar-heatmap/dist/vue-calendar-heatmap.common.js?v=87363113' does not provide an export named 'default'

**Comment by toniengelhardt** [comment]
Have the same problem as @hojas.

**Comment by antfu** [comment]
Should be fixed with https://github.com/nuxt/framework/pull/2521 in the latest version of. bridge

**Comment by richardeschloss** [comment]
Thank you @antfu for this.

**Comment by dallman2** [comment]
running into this issue with threejs. also, adding `three` to the exclude list does not fix the issue

**Comment by PeterLS** [comment]
Faced the same issue when including `import bootstrap from 'bootstrap'.`

**Comment by videate-miguel** [comment]
This is with Uppy JS

Putting Uppy in the excluded dependencies does not work, below is my config and the error I get 
![image](https://user-images.githubusercontent.com/85573434/186780625-a858d990-c7db-4d7d-b134-426ff9203316.png)
![image](https://user-images.githubusercontent.com/85573434/186780654-35277a99-bded-4bd6-93a1-62dceff59908.png)


`Uncaught SyntaxError: The requested module '/node_modules/mime-match/index.js?v=2b94e689' does not provide an export named 'default' (at Restricter.js?v=2b94e689:3:8)`

**Comment by imanmalekian31** [comment]
`hammerjs`
![Screenshot from 2022-09-13 16-44-51](https://user-images.githubusercontent.com/58827166/189898340-f18503f5-8838-408c-b46d-0c7ed392cd5b.png)

**Comment by justindefodji** [comment]
Faced the same issue when including `import { Line } from "vue-chartjs/legacy"` and `import Vue from "vue"` in plugins

**Comment by imanmalekian31** [comment]
`clipboard.js`
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/clipboard/dist/clipboard.js?v=d9db4321' does not provide an export named 'default' (at index.ts:1:8)
